//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Vivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vivienda()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int id { get; set; }
        public int numeroCuartos { get; set; }
        public int numeroBanos { get; set; }
        public decimal tamano { get; set; }
        public int numPisos { get; set; }
        public string accesorios { get; set; }
        public int tipoViviendaId { get; set; }
        public int agenciaId { get; set; }

        [JsonIgnore]
        public virtual Agencia Agencia { get; set; }

        [JsonIgnore]
        public virtual TipoVivienda TipoVivienda { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
